from __future__ import annotations

from sqlalchemy import func, select
from sqlalchemy.orm import Session

from app.models import Group, Role, User
from app.security.passwords import generate_password, hash_password, verify_password

ADMINS_GROUP = "Admins"
_ROLE_GROUP_NAME = {
    Role.admin: ADMINS_GROUP,
    Role.incident_commander: "Incident Commanders",
    Role.read_only: "Read-only",
}


def _norm(email: str) -> str:
    return email.strip().lower()


def _get_or_create_group(db: Session, role: Role) -> Group:
    name = _ROLE_GROUP_NAME[role]
    group = db.scalar(select(Group).where(Group.name == name))
    if group is None:
        group = Group(name=name, role=role, is_system=(role == Role.admin))
        db.add(group)
        db.flush()
    return group


def bootstrap_admin(db: Session, admin_email: str) -> tuple[User, str | None]:
    existing = db.scalar(select(User).where(User.is_protected_admin.is_(True)))
    if existing is not None:
        return existing, None
    admins = _get_or_create_group(db, Role.admin)
    password = generate_password()
    admin = User(
        email=_norm(admin_email),
        name="Administrator",
        password_hash=hash_password(password),
        is_protected_admin=True,
        must_change_password=True,
    )
    admin.groups = [admins]
    db.add(admin)
    db.flush()
    return admin, password


def create_user(
    db: Session,
    *,
    email: str,
    name: str,
    role: Role,
    password: str | None = None,
    must_change_password: bool = False,
) -> User:
    norm = _norm(email)
    if db.scalar(select(User).where(func.lower(User.email) == norm)):
        raise ValueError(f"A user with email {norm} already exists")
    group = _get_or_create_group(db, role)
    user = User(
        email=norm,
        name=name,
        password_hash=hash_password(password) if password else None,
        # True when a temp password is generated by the admin UI; the user must
        # change it on first login (Phase 1 flow). False when no password is set
        # (e.g., SSO-only users created without a local credential).
        must_change_password=must_change_password,
    )
    user.groups = [group]
    db.add(user)
    db.flush()
    return user


def set_user_groups(db: Session, user: User, group_ids: list[int]) -> None:
    groups = list(db.scalars(select(Group).where(Group.id.in_(group_ids)))) if group_ids else []
    if user.is_protected_admin and not any(g.name == ADMINS_GROUP for g in groups):
        raise ValueError("Cannot remove the protected admin from the Admins group")
    user.groups = groups
    db.flush()


def deactivate_user(db: Session, user: User) -> None:
    if user.is_protected_admin:
        raise ValueError("Cannot deactivate the protected admin")
    user.is_active = False
    db.flush()


def authenticate_local(db: Session, email: str, password: str) -> User | None:
    user = db.scalar(select(User).where(func.lower(User.email) == _norm(email)))
    if user is None or not user.is_active or not user.password_hash:
        return None
    if not verify_password(password, user.password_hash):
        return None
    return user
