"""initial

Revision ID: 0001_initial
Revises:
Create Date: 2026-06-20 12:30:49.833930

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

import app.crypto

# revision identifiers, used by Alembic.
revision: str = '0001_initial'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Define shared enum types once to avoid "type already exists" errors
# 'role' is used by both groups.role and sso_settings.auto_provision_role
role_enum = sa.Enum('admin', 'incident_commander', 'read_only', name='role')
severity_enum = sa.Enum('SEV1', 'SEV2', 'SEV3', name='severity')
incident_status_enum = sa.Enum('open', 'closed', name='incident_status')


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('slack_channel_name_template', sa.String(length=120), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('google_settings',
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('client_id', sa.String(length=255), nullable=True),
    sa.Column('client_secret', app.crypto.EncryptedString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('role', role_enum, nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('slack_settings',
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('client_id', sa.String(length=255), nullable=True),
    sa.Column('client_secret', app.crypto.EncryptedString(), nullable=True),
    sa.Column('signing_secret', app.crypto.EncryptedString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('smtp_settings',
    sa.Column('host', sa.String(length=255), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('password', app.crypto.EncryptedString(), nullable=True),
    sa.Column('from_address', sa.String(length=320), nullable=True),
    sa.Column('use_tls', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sso_settings',
    sa.Column('sso_enabled', sa.Boolean(), nullable=False),
    sa.Column('allow_local_login', sa.Boolean(), nullable=False),
    sa.Column('allowed_domains', sa.Text(), nullable=True),
    # role enum already created by groups table above; use create_type=False to avoid duplicate
    sa.Column('auto_provision_role', sa.Enum('admin', 'incident_commander', 'read_only', name='role', create_type=False), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('google_sub', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('is_protected_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('google_sub')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('google_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_email', sa.String(length=320), nullable=False),
    sa.Column('account_sub', sa.String(length=255), nullable=True),
    sa.Column('refresh_token', app.crypto.EncryptedString(), nullable=False),
    sa.Column('calendar_id', sa.String(length=255), nullable=False),
    sa.Column('scopes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_google_connections_account_email'), 'google_connections', ['account_email'], unique=False)
    op.create_table('invites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invites_email'), 'invites', ['email'], unique=False)
    op.create_table('slack_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.String(length=64), nullable=False),
    sa.Column('team_name', sa.String(length=255), nullable=True),
    sa.Column('bot_user_id', sa.String(length=64), nullable=True),
    sa.Column('app_id', sa.String(length=64), nullable=True),
    sa.Column('bot_token', app.crypto.EncryptedString(), nullable=False),
    sa.Column('scopes', sa.Text(), nullable=True),
    sa.Column('is_enterprise_install', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_slack_connections_team_id'), 'slack_connections', ['team_id'], unique=True)
    op.create_table('user_groups',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'group_id')
    )
    op.create_table('incidents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('severity', severity_enum, nullable=False),
    sa.Column('status', incident_status_enum, nullable=False),
    sa.Column('is_private', sa.Boolean(), nullable=False),
    sa.Column('slack_connection_id', sa.Integer(), nullable=True),
    sa.Column('google_connection_id', sa.Integer(), nullable=True),
    sa.Column('slack_channel_id', sa.String(length=64), nullable=True),
    sa.Column('slack_channel_name', sa.String(length=120), nullable=True),
    sa.Column('slack_channel_url', sa.Text(), nullable=True),
    sa.Column('meet_url', sa.Text(), nullable=True),
    sa.Column('calendar_event_id', sa.String(length=255), nullable=True),
    sa.Column('creation_state', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('closed_by', sa.Integer(), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['closed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['google_connection_id'], ['google_connections.id'], ),
    sa.ForeignKeyConstraint(['slack_connection_id'], ['slack_connections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('incidents')
    op.drop_table('user_groups')
    op.drop_index(op.f('ix_slack_connections_team_id'), table_name='slack_connections')
    op.drop_table('slack_connections')
    op.drop_index(op.f('ix_invites_email'), table_name='invites')
    op.drop_table('invites')
    op.drop_index(op.f('ix_google_connections_account_email'), table_name='google_connections')
    op.drop_table('google_connections')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('sso_settings')
    op.drop_table('smtp_settings')
    op.drop_table('slack_settings')
    op.drop_table('groups')
    op.drop_table('google_settings')
    op.drop_table('app_settings')
    # Drop enum types that were created during upgrade
    # (Alembic autogenerate does not drop them automatically)
    severity_enum.drop(op.get_bind(), checkfirst=True)
    incident_status_enum.drop(op.get_bind(), checkfirst=True)
    role_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
